#!/usr/bin/env bash
# Configure NGINX Server so that /redirect_me
# is directing to another page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/layan2k permanent;/" /etc/nginx/sites-available/default
service nginx start
