#!/usr/bin/env bash
# Installs HA-Proxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

config="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 614-web-01 3.238.253.91:80 check\n\tserver 614-web-02 35.237.111.104:80 check"
sudo echo -e "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
