#!/usr/bin/env bash
#display hours from 0 to 12
#display i from 1 to 59

j=0

while [ $j -le 12 ]
do
    echo "Hour: $j"
    i=1
    while [ $i -lt 60 ]
    do
	echo "$i"
	((i++))
    done
    ((j++))
done
