#!/usr/bin/env bash
#checks if theschool school exists and prints its content if it does

    if [ -e school ]
    then
    echo "school exists"

    if [ -s school ]
    then
	echo "school is not empty"
    else
	echo "school is empty"
    fi

    if [ -f school ]
    then
	echo "school is a regular file"
    fi
    else
        echo "school does not exist"
    fi
